export type ProductEntity = {
  id: string;
  storeId: string;
  name: string;
  content: string | null;
  material: string | null;
  color: string | null;
  manufacturerName: string | null;
  manufactureCountry: string | null;
  manufactureDate: string | null;
  caution: string | null;
  qualityGuaranteeStandard: string | null;
  asManagerName: string | null;
  asPhoneNumber: string | null;
  shippingFee: number | null;
  extraShippingFee: number | null;
  shippingCompany: string | null;
  deliveryPeriod: string | null;
  returnExchangePolicy: string | null;
  returnShippingFee: number | null;
  exchangeShippingFee: number | null;
  price: number;
  isSoldOut: boolean;
  categoryId: string;
  imageUrl: string | null;
  imageKey: string | null;
  discountRate: number | null;
  discountStartTime: Date | null;
  discountEndTime: Date | null;
  createdAt: Date;
  updatedAt: Date;
};
