### 환경 설정
@base = http://localhost:3000
@accessToken = 

### 새 상점 등록 (관리자)
POST {{base}}/stores
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "CUID",
  "name": "CODI-IT",
  "createdAt": "2025-06-01T12:00:00.000Z",
  "updatedAt": "2025-06-01T13:00:00.000Z",
  "userId": "CUID",
  "address": "서울특별시 강남구 테헤란로 123",
  "detailAddress": "1동 1106호",
  "phoneNumber": "010-1234-5678",
  "content": "저희는 CODI-IT 입니다.",
  "image": "https://example.com/image.jpg"
}

### 스토어 수정
PATCH {{base}}/stores/{storeId}
Authorization: Bearer {{accessToken}}

### 스토어 상세 조회
GET {{base}}/stores/{storeId}
Authorization: Bearer {{accessToken}}

### 내 스토어 상세 조회
GET {{base}}/stores/detail/my
Authorization: Bearer {{accessToken}}

### 내 스토어 등록 상품 조회
GET {{base}}/stores/detail/my/products
Authorization: Bearer {{accessToken}}

### 관심 스토어 등록
POST {{base}}/stores/{storeId}/favorite
Authorization: Bearer {{accessToken}}

### 관심 스토어 해제
DELETE {{base}}/stores/{storeId}/favorite
Authorization: Bearer {{accessToken}}
Content-Type: application/json
