### 환경 설정
@base = http://localhost:3001
@accessToken = 
@refreshToken = 

### 회원가입
POST {{base}}/users
Content-Type: application/json

{
  "name": "김유저",
  "email": "user01@example.com",
  "password": "password123",
  "type": "BUYER"
}

### 내 정보 조회
GET {{base}}/users/me
Authorization: Bearer {{accessToken}}

### 내 정보 수정
PATCH {{base}}/users/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "CUID",
  "name": "김유저",
  "email": "email@example.com",
  "type": "BUYER",
  "points": 999,
  "createdAt": "2025-05-29T06:00:41.976Z",
  "updatedAt": "2025-05-29T06:00:41.976Z",
  "grade": {
    "name": "green",
    "id": "grade_green",
    "rate": 5,
    "minAmount": 1000000
  },
  "image": "https://sprint-be-project.s3.ap-northeast-2.amazonaws.com/codiit/1749477485230-user_default.png"
}

### 관심 스토어 조회
GET {{base}}/users/me/likes
Authorization: Bearer {{accessToken}}

### 회원 탈퇴
DELETE {{base}}/users/delete
Authorization: Bearer {{accessToken}}
